version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - postgres
    ports:
      - 4000:4000

  postgres:
    container_name: database
    image: postgres
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - category_task:/var/lib/postgresql/data

volumes:
  category_task:
